---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  revisionHistoryLimit: {{ .Values.deployment.revisionHistoryLimit }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      terminationGracePeriodSeconds: 30
      initContainers:
        - name: worker
          image: {{ .Values.deployment.repository }}:{{ .Values.deployment.tag }}
          imagePullPolicy: {{ .Values.deployment.pullPolicy }}
          restartPolicy: Always
          command: ["bundle", "exec", "sidekiq"]
          args: ["-t", "25"]
          env:
            {{- range .Values.deployment.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
            - name: DB_HOST
              value: {{ .Release.Name }}-postgresql
            - name: POSTGRES_DB
              value: {{ .Values.postgresql.auth.database }}
            - name: POSTGRES_USER
              value: {{ .Values.postgresql.auth.username }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgresql.auth.existingSecret | default (printf "%s-postgresql" .Release.Name) }}
                  key: password
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-redis
                  key: {{ .Values.redis.auth.password | default "redis-password" }}
            - name: REDIS_URL
              {{- if .Values.redis.auth.enabled}}
              value: redis://:$(REDIS_PASSWORD)@$(REDIS_HOST):6379/0
              {{- else }}
              value: redis://:@$(REDIS_HOST):6379/0
              {{- end }}
          {{- if .Values.deployment.extraEnvVarsCM }}
          envFrom:
            - configMapRef:
                name: {{ .Values.deployment.extraEnvVarsCM  }}
          {{- end }}
          {{- if .Values.deployment.extraEnvVarsSecret }}
          envFrom:
            - secretRef:
                name: {{ .Values.deployment.extraEnvVarsSecret }}
          {{- end }}
          {{- if .Values.deployment.securityContext }}
          securityContext:
              {{- with .Values.deployment.securityContext }}
              {{- toYaml . | nindent 14 }}
              {{- end }}
          {{- end }}
      containers:
        - name: {{ .Release.Name }}
          image: {{ .Values.deployment.repository }}:{{ .Values.deployment.tag }}
          imagePullPolicy: {{ .Values.deployment.pullPolicy }}
          env:
            - name: DB_HOST
              value: {{ .Release.Name }}-postgresql
            - name: POSTGRES_DB
              value: {{ .Values.postgresql.auth.database }}
            - name: POSTGRES_USER
              value: {{ .Values.postgresql.auth.username }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgresql.auth.existingSecret | default (printf "%s-postgresql" .Release.Name) }}
                  key: password
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-redis
                  key: {{ .Values.redis.auth.password | default "redis-password" }}
            - name: REDIS_URL
              {{- if .Values.redis.auth.enabled}}
              value: redis://:$(REDIS_PASSWORD)@$(REDIS_HOST):6379/0
              {{- else }}
              value: redis://:@$(REDIS_HOST):6379/0
              {{- end }}
            {{- range .Values.deployment.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
          {{- if .Values.deployment.extraEnvVarsCM }}
          envFrom:
            - configMapRef:
                name: {{ .Values.deployment.extraEnvVarsCM  }}
          {{- end }}
          {{- if .Values.deployment.extraEnvVarsSecret }}
          envFrom:
            - secretRef:
                name: {{ .Values.deployment.extraEnvVarsSecret }}
          {{- end }}
          ports:
            - containerPort: {{ .Values.deployment.port }}
          {{- if .Values.deployment.securityContext }}
          securityContext:
              {{- with .Values.deployment.securityContext }}
              {{- toYaml . | nindent 14 }}
              {{- end }}
          {{- end }}
          readinessProbe:
            tcpSocket:
              port: {{ .Values.deployment.port }}
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            tcpSocket:
              port: {{ .Values.deployment.port }}
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          volumeMounts:
            - name: data
              mountPath: /rails/storage
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data-{{ .Release.Name }}
      {{- if .Values.deployment.podSecurityContext }}
      securityContext:
          {{- with .Values.deployment.podSecurityContext }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
      {{- end }}
