---
apiVersion: v2
name: maybe-finance
description: A Helm chart for deploying maybe-finance into kubernetes clusters
type: application
version: 0.1.1
appVersion: "0.4.3"
home: https://github.com/vicsufer/charts/tree/master/charts/maybe-finance
icon: https://avatars.githubusercontent.com/u/80786585?s=200&v=4
sources:
  - https://github.com/maybe-finance/maybe
keywords:
  - maybe-finance
  - budget
  - finance

dependencies:
  - name: postgresql
    version: 15.5.38
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled

annotations:
  artifacthub.io/links: |
    - name: Chart Source
      url: https://github.com/vicsufer/charts/tree/master/charts/maybe-finance
    - name: Upstream Project
      url: https://github.com/maybe-finance/maybe
  artifacthub.io/category: streaming-messaging
  artifacthub.io/maintainers: |
    - name: vicsufer
  artifacthub.io/operator: "false"
  artifacthub.io/prerelease: "false"
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/signKey: |
    fingerprint: 1C2692BCB57D5153875BBB01CEAC618DF9046E80
    url: https://keybase.io/vicsufer/pgp_keys.asc
