---
service:
  type: ClusterIP

deployment:
  repository: ghcr.io/maybe-finance/maybe
  tag: 0.5.0
  replicaCount: 1
  revisionHistoryLimit: 3
  port: 3000
  pullPolicy: IfNotPresent
  podSecurityContext:
    fsGroup: 1000
    runAsUser: 1000
    runAsGroup: 1000
    runAsNonRoot: true
  securityContext:
    allowPrivilegeEscalation: false
  extraEnvVarsCM: ""
  extraEnvVarsSecret: ""
  env: #[] # https://github.com/maybe-finance/maybe/blob/main/.env.example
    # - name: RAILS_ASSUME_SSL
    #   value: false
    # - name: RAILS_FORCE_SSL
    #   value: false
    # - name: GOOD_JOB_EXECUTION_MODE
    #   value: async
    - name: SECRET_KEY_BASE # Required
      value: "a7523c3d0ae56415046ad8abae168d71074a79534a7062258f8d1d51ac2f76d3c3bc86d86b6b0b307df30d9a6a90a2066a3fa9e67c5e6f374dbd7dd4e0778e13"
    - name: SELF_HOSTING_ENABLED # Required
      value: "true"

redis:
  enabled: true
  auth:
    enabled: true
    password: redis-password
  replica:
    replicaCount: 1


storage:
  accessModes: ReadWriteOnce
  size: 2Gi

postgresql:
  primary:
    persistence:
      size: 4Gi
  auth:
    username: maybe
    password: password
    database: maybe
    #existingSecret: "" # Use this value to mount your own database secret

ingress:
  create: false
  annotations: { }
  # cert-manager.io/cluster-issuer: ""
  tls:
    - secretName: maybe-general-tls
      hosts:
        - maybe.mydomain.com
  hosts:
    - host: maybe.mydomain.com
      paths:
        - path: /
          pathType: ImplementationSpecific

extraObjects: [ ]
# - |
#   apiVersion: bitnami.com/v1alpha1
#   kind: SealedSecret
#   metadata:
#     name: database-password
#     namespace: mynamepace
#   spec:
#     encryptedData:
#       postgres-password: <Your sealed secret>
#       password: <Your sealed secret>
#     template:
#       metadata:
#         name: database-password
#         namespace: maybe-finance
